export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  OPERATOR = 'OPERATOR',
  ADMIN = 'ADMIN',
  DIREKTOR = 'DIREKTOR',
  BOSS = 'BOSS',
  BUGALTERIYA = 'BUGALTERIYA',
  PTO = 'PTO',
  SNABJENIYA = 'SNABJENIYA',
  SKLAD = 'SKLAD',
  PRORAB = 'PRORAB',
  HAYDOVCHI = 'HAYDOVCHI',
  MODERATOR = 'MODERATOR',
  WORKER = 'WORKER',
  POSTAVSHIK = 'POSTAVSHIK',
}

export enum SubscriptionTier {
  ODDIY = 'ODDIY',
  PRO = 'PRO',
  ENTERPRISE = 'ENTERPRISE',
}
